changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - rn:break
    - title: Exciting New Features 🎉
      labels:
        - rn:feat
    - title: Fixes 🔧
      labels:
        - rn:fix
    - title: Other Changes
      labels:
        - "*"
