changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - rn:breaking
    - title: Exciting New Features 🎉
      labels:
        - rn:feature
    - title: Fixes 🔧
      labels:
        - rn:fix
    - title: Documentation 📄
      labels:
        - rn:documentation
    - title: CI 🤖
      labels:
        - rn:cicd
    - title: Other Changes
      labels:
        - "*"
