name: "Pull Request Merge"

on:
  pull_request_target:
    types:
      - closed
      - edited

jobs:
  ###################################################
  # Assign labels on merge to generate Release Notes
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges
  ###################################################
  if_merged:
    name: "PR Merged"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          echo "The PR was merged"
      # V3 is not used as we hit following issue: https://github.com/actions/labeler/issues/107
      # - uses: bcoe/conventional-release-labels@v1.3.0
      #  with:
      #    token: "${{ secrets.GITHUB_TOKEN }}"
      #    type_labels: '{"Feat": "rn:feature", "Fix": "rn:fix", "Breaking":"rn:breaking", "Doc":"rn:documentation", "CI":"rn:cicd"}'
      - uses: actions/checkout@v3
      - name: dump github event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set Label
        run: echo "LABEL=$(echo 'rn:${{ github.event.pull_request.title }}' | cut -d ':' -f 1,2)" >> $GITHUB_ENV
      - name: Echo Label
        run: echo $LABEL
      - name: Create Label
        run: gh label create "${{ env.LABEL }}"
      - name: Manual labelling!
        run: gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.LABEL }}"
